---
apiVersion: v1
kind: Service
metadata:
  name: minepod-service
  labels:
    app: minepod-service

spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25565
      name: "25565"
      protocol: TCP

    - port: 25575
      targetPort: 25575
      name: "25575"
      protocol: TCP
  selector:
    app: minepod
...